// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.caprado.romgi.ncch_decrypt

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private open class NcchDecryptApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/**
 * Methods Dart calls into Kotlin.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface NcchDecryptHostApi {
  /**
   * Decrypts every populated NCCH partition of the CCI (.3ds) file at
   * [cciPath] in place, using key material derived from the user-supplied
   * [boot9Path] (a dump of their own console's ARM9 bootROM). Partitions
   * using seed crypto additionally need [seeddbPath] (a user-supplied
   * seeddb.bin) to look up their per-title seed; if a seed-using partition
   * is hit and [seeddbPath] is null or lacks that title's seed, this
   * throws rather than guessing. Also throws if boot9 is invalid/mismatched.
   */
  fun decryptCci(cciPath: String, boot9Path: String, seeddbPath: String?, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by NcchDecryptHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NcchDecryptApiPigeonCodec()
    }
    /** Sets up an instance of `NcchDecryptHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NcchDecryptHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.romgi.NcchDecryptHostApi.decryptCci$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cciPathArg = args[0] as String
            val boot9PathArg = args[1] as String
            val seeddbPathArg = args[2] as String?
            api.decryptCci(cciPathArg, boot9PathArg, seeddbPathArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
